### ISSUE TITLE
how to change the webservers in daemon mode?

### ISSUE THREAD

**Issue by krishraghuram** [iridium77/htpdate#2]
I tried this - 
`sudo htpdate -D intranet.iitg.ernet.in`
But I get this,
`htpdate already running`

Checking this,
`ps aux | grep htpdate`
I get,
`/usr/sbin/htpdate -D -s -i /var/run/htpdate.pid www.pool.ntp.org www.ntp.br www.wikipedia.org`
Is there any way to sync to my local webservers instead of syncing to wikipedia and ntp?

**Comment by iridium77** [comment]
This is totally a general linux question.
1. Kill that job, then try again. It should work.
2. To make it still work after restarting your machine, find the auto-start script, change the server names to yours.

**Comment by krishraghuram** [comment]
Yes. I realised it few hours later, and figured it out.
I should have probably asked in stackoverflow or something. 
Sorry.
